MassEmail/Controllers/AjaxController.cs
using LNF;
using LNF.Mail;
using System.Linq;
using System.Web.Mvc;

namespace MassEmail.Controllers
{
    public class AjaxController : MassEmailController
    {
        public AjaxController(IProvider provider) : base(provider) { }

        [HttpGet, Route("ajax")]
        public ActionResult Test()
        {
            return Json(new { test = "Hello World!" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost, Route("ajax/recipients")]
        public ActionResult Recipients(MassEmailRecipientArgs args)
        {
            var result = Provider.Mail.MassEmail.GetRecipients(args).OrderBy(x => x.Email).ToList();
            return Json(result);
        }
    }
}

MassEmail/Controllers/HomeController.cs
using LNF;
using LNF.Data;
using LNF.Mail;
using MassEmail.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MassEmail.Controllers
{
    [Authorize]
    public class HomeController : MassEmailController
    {
        private List<string> _errors;
        private List<Attachment> _attachments;

        public HomeController(IProvider provider) : base(provider) { }

        [HttpGet, Route("")]
        public ActionResult Index()
        {
            var selectedTab = GetSelectedTab();

            ViewBag.SelectedTab = selectedTab;
            ViewBag.Errors = new List<string>();
            ViewBag.Message = string.Empty;

            if (selectedTab == "admin")
            {
                return RedirectToAction("Admin");
            }
            else
            {
                var model = new HomeModel
                {
                    From = CurrentUser.Email,
                    DisplayName = CurrentUser.DisplayName,
                    SelectedValues = JsonConvert.SerializeObject(new int[0])
                };

                InitModel(model, selectedTab);

                return View(model);
            }
        }

        [HttpPost, Route("")]
        public ActionResult Index(HomeModel model)
        {
            InitModel(model, model.SelectedTab);
            ViewBag.SelectedTab = model.SelectedTab;

            ViewBag.Message = string.Empty;

            var group = model.SelectedTab;

            if (string.IsNullOrEmpty(group))
                throw new Exception("Cannot determine recipient group.");

            var values = JsonConvert.DeserializeObject<IEnumerable<int>>(model.SelectedValues);

            _errors = new List<string>();

            if (values.Count() == 0)
                _errors.Add("You have not selected any recipients.");

            if (string.IsNullOrEmpty(model.From))
                _errors.Add("From address is required.");

            if (string.IsNullOrEmpty(model.DisplayName))
                _errors.Add("Display name is required.");

            if (string.IsNullOrEmpty(model.Subject))
                _errors.Add("Subject is required.");

            if (string.IsNullOrEmpty(model.Body))
                _errors.Add("Body is required.");

            if (_errors.Count == 0)
            {
                var args = new MassEmailSendArgs
                {
                    ClientID = CurrentUser.ClientID,
                    Caller = "MassEmail.Controllers.HomeController.Index",
                    Group = group,
                    Values = values,
                    From = model.From,
                    CC = model.CC,
                    DisplayName = model.DisplayName,
                    Subject = model.Subject,
                    Body = model.Body
                };

                if (GetAttachments())
                {
                    if (_attachments.Count > 0)
                    {
                        var guid = Provider.Mail.Attachment.Attach(_attachments);
                        args.Attachments = guid;
                    }

                    var sent = Provider.Mail.SendMassEmail(args);

                    ViewBag.Message = $"Mail sent OK! Emails sent: {sent}";
                }
            }

            ViewBag.Errors = _errors ?? new List<string>(); // empty list if there were no errors

            return View(model);
        }

        [HttpGet, Route("admin")]
        public ActionResult Admin(bool active = true, int? emailId = null)
        {
            var invalid = GetInvalidEmails(active);

            var model = new AdminModel
            {
                IsAdmin = IsAdmin(),
                SelectedTab = "admin",
                InvalidEmails = invalid,
                ShowDeleted = !active,
                EditEmailID = 0
            };

            if (emailId.HasValue)
            {
                var modify = invalid.FirstOrDefault(x => x.EmailID == emailId.GetValueOrDefault());
                if (modify != null)
                {
                    model.EditEmailID = modify.EmailID;
                    model.EditDisplayName = modify.DisplayName;
                    model.EditEmailAddress = modify.EmailAddress;
                }
            }

            return View(model);
        }

        [HttpGet, Route("admin/invalid-email/{command}")]
        public ActionResult AdminInvalidEmailCommand(string command, int emailId)
        {
            bool value = command != "delete";
            Provider.Mail.MassEmail.SetInvalidEmailActive(emailId, value);
            return RedirectToAction("Admin");
        }

        [HttpPost, Route("admin")]
        public ActionResult Admin(AdminModel model)
        {
            IInvalidEmail invalidEmail;

            ViewBag.ErrorMessage = string.Empty;

            if (EmailIsValid(model.EditEmailAddress))
            {
                if (model.EditEmailID == 0)
                {
                    invalidEmail = new InvalidEmailItem
                    {
                        DisplayName = model.EditDisplayName,
                        EmailAddress = model.EditEmailAddress,
                        IsActive = true
                    };

                    Provider.Mail.MassEmail.AddInvalidEmail(invalidEmail);

                    return RedirectToAction("Admin");
                }
                else
                {
                    invalidEmail = new InvalidEmailItem
                    {
                        EmailID = model.EditEmailID,
                        DisplayName = model.EditDisplayName,
                        EmailAddress = model.EditEmailAddress,
                        IsActive = true
                    };

                    Provider.Mail.MassEmail.ModifyInvalidEmail(invalidEmail);

                    return RedirectToAction("Admin");
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Invalid email address.";

                model.IsAdmin = IsAdmin();
                model.SelectedTab = "admin";
                model.InvalidEmails = GetInvalidEmails(true);
                model.ShowDeleted = true;

                return View(model);
            }
        }

        [Route("nav/{tab}")]
        public ActionResult Navigate(string tab)
        {
            Session["SelectedTab"] = tab;
            return RedirectToAction("Index");
        }

        private bool IsAdmin()
        {
            return CurrentUser.HasPriv(ClientPrivilege.Administrator | ClientPrivilege.Developer);
        }

        private string GetSelectedTab()
        {
            if (Session["SelectedTab"] == null)
                Session["SelectedTab"] = "privilege";

            var result = Convert.ToString(Session["SelectedTab"]);

            Session.Remove("SelectedTab");

            return result;
        }

        private void InitModel(MassEmailModel model, string selectedTab)
        {
            model.IsAdmin = IsAdmin();
            model.SelectedTab = selectedTab;
            model.Privs = Provider.Data.Client.GetPrivs();
            model.Communities = Provider.Data.Client.GetCommunities();
            model.Managers = Provider.Data.Client.AllActiveManagers();
            model.Tools = Provider.Scheduler.Resource.AllActiveResources();
            model.Areas = Provider.Data.Room.GetPassbackRooms();
        }

        private bool GetAttachments()
        {
            _attachments = new List<Attachment>();
            _errors = new List<string>();

            var result = true;

            for (var x = 0; x < Request.Files.Count; x++)
            {
                var file = Request.Files[x];

                if (file != null && !string.IsNullOrEmpty(file.FileName))
                {
                    if (file.ContentLength > 0)
                    {
                        if (IsAllowedFileType(file))
                        {
                            using (var ms = new MemoryStream(file.ContentLength))
                            {
                                file.InputStream.CopyTo(ms);
                                var a = new Attachment
                                {
                                    FileName = file.FileName,
                                    Data = ms.ToArray()
                                };
                                _attachments.Add(a);
                            }
                        }
                        else
                        {
                            _errors.Add($"File {file.FileName}: file type is not allowed.");
                            result = false;
                        }
                    }
                    else
                    {
                        _errors.Add($"File {file.FileName}: file is empty.");
                        result = false;
                    }
                }
            }

            return result;
        }

        private bool IsAllowedFileType(HttpPostedFileBase file)
        {
            var ext = Path.GetExtension(file.FileName);
            return GetAllowedFileTypes().Contains(ext);
        }

        private string[] GetAllowedFileTypes()
        {
            var setting = ConfigurationManager.AppSettings["AllowedFileTypes"];

            if (string.IsNullOrEmpty(setting))
                throw new Exception("Missing required appSetting: AllowedFileTypes");

            return setting.Split(',');
        }

        private bool EmailIsValid(string email)
        {
            if (string.IsNullOrEmpty(email))
                return false;

            try
            {
                var ma = new System.Net.Mail.MailAddress(email);
                return true;
            }
            catch
            {
                return false;
            }
        }

MassEmail/Views/Home/Admin.cshtml
@using MassEmail.Models;

@model AdminModel
@{
    ViewBag.Title = "Admin";
    string buttonText = Model.EditEmailID > 0 ? "Save" : "Add";
    string errmsg = ViewBag.ErrorMessage;
}

<h4>Mass Email Admin</h4>

@Html.Partial("_TabMenu", Model)


@if (Model.IsAdmin)
{
    <div class="row">
        <div class="col-6">
            <h5>Invalid Email Address List</h5>

            @if (!string.IsNullOrEmpty(errmsg))
            {
                <div class="alert alert-danger mt-4" role="alert">@errmsg</div>
            }

            <div class="mt-4 mb-4">
                @using (Html.BeginForm("Admin", "Home", FormMethod.Post, new { @class = "mb-2" }))
                {
                    @Html.HiddenFor(x => x.EditEmailID)
                    <div class="form-row">
                        <div class="col">
                            @Html.TextBoxFor(x => x.EditDisplayName, new { @class = "form-control", placeholder = "Name" })
                        </div>
                        <div class="col">
                            @Html.TextBoxFor(x => x.EditEmailAddress, new { @class = "form-control", placeholder = "Email" })
                        </div>
                        <div class="col">
                            <button type="submit" class="btn btn-outline-primary">@buttonText</button>
                        </div>
                    </div>
                }

                <label class="ml-1">
                    @Html.CheckBox("ShowDeleted", Model.ShowDeleted, new { @class = "show-deleted" }) Show Deleted
                </label>
            </div>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="width: 240px;">Name</th>
                        <th>Email</th>
                        <th style="width: 140px;">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var i in Model.InvalidEmails)
                    {
                        <tr class="@(i.IsActive ? "active" : "inactive")">
                            <td>@i.DisplayName</td>
                            <td>@i.EmailAddress</td>
                            <td class="text-right">
                                @if (i.IsActive)
                                {
                                    <div>
                                        @Html.ActionLink("modify", "Admin", new { emailId = i.EmailID }) |
                                        @Html.ActionLink("delete", "AdminInvalidEmailCommand", new { command = "delete", emailId = i.EmailID })
                                    </div>
                                }
                                else
                                {
                                    <div>
                                        @Html.ActionLink("undelete", "AdminInvalidEmailCommand", new { command = "undelete", emailId = i.EmailID })
                                    </div>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}
else
{
    <div class="alert alert-danger" role="alert">
        You do not have permission to access this page.
    </div>
}

<hr />

@section scripts{
    <script>
        $('#tab1 a[id="admin-tab"]').tab('show');

        $(".show-deleted").on("change", function (e) {
            var active = $(this).prop("checked") ? "false" : "true";
            window.location = '@Url.Action("Admin")?active=' + active;
        })
    </script>
}

MassEmail/Views/Home/Index.cshtml
@using MassEmail.Models;

@model HomeModel
@{
    ViewBag.Title = "Mass Email";
    List<string> errors = ViewBag.Errors;
    string message = ViewBag.Message;
}

<h4>Send Email to User Groups</h4>

@Html.Partial("_TabMenu", Model)

<hr class="mt-0" />

@using (Html.BeginForm("Index", "Home", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data", id = "form1" }))
{
    @Html.HiddenFor(x => x.SelectedTab, new { @class = "selected-tab" })
    @Html.HiddenFor(x => x.SelectedValues, new { @class = "selected-values" })

    <div class="form-group row">
        <label for="From" class="col-sm-1 col-form-label">From</label>
        <div class="col-sm-3">
            <input type="text" class="form-control" id="From" name="From" value="@Model.From">
        </div>
    </div>
    <div class="form-group row">
        <label for="CC" class="col-sm-1 col-form-label">CC</label>
        <div class="col-sm-3">
            <input type="text" class="form-control" id="CC" name="CC" value="@Model.CC" placeholder="Please type any CC email addresses here">
        </div>
    </div>
    <div class="form-group row">
        <label for="DisplayName" class="col-sm-1 col-form-label">Display Name</label>
        <div class="col-sm-3">
            <input type="text" class="form-control" id="DisplayName" name="DisplayName" value="@Model.DisplayName">
        </div>
    </div>
    <div class="form-group row">
        <label for="Subject" class="col-sm-1 col-form-label">Subject</label>
        <div class="col-sm-3">
            <input type="text" class="form-control" id="Subject" name="Subject" value="@Model.Subject" placeholder="You must have a subject">
        </div>
    </div>
    <div class="form-group row">
        <label for="Attachments" class="col-sm-1 col-form-label">Attachments</label>
        <div class="col-sm-3">
            <p class="form-control-plaintext">
                <input type="file" id="Attachments" name="Attachments" multiple>
            </p>
        </div>
    </div>
    <div class="form-group row">
        <label for="Body" class="col-sm-1 col-form-label">Body</label>
        <div class="col-sm-6">
            <textarea class="form-control" id="Body" name="Body" placeholder="Please type the body here" style="height: 200px; resize: both;">@Model.Body</textarea>
        </div>
    </div>
    <div class="form-group row">
        <div class="offset-1 col-6">
            <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#recipeints-modal">View Recipients</button>
            <button type="submit" class="btn btn-outline-primary">Send Email</button>
            @if (errors.Count > 0)
            {
                <div class="alert alert-danger mt-3" role="alert">
                    @if (errors.Count == 1)
                    {
                        <span>@errors[0]</span>
                    }
                    else
                    {
                        <ul>
                            @foreach (var e in errors)
                            {
                                <li>@e</li>
                            }
                        </ul>
                    }
                </div>
            }
            else if (!string.IsNullOrEmpty(message))
            {
                <div class="alert alert-success mt-3" role="alert">@message</div>
            }
        </div>
    </div>
}

<div class="modal fade" id="recipeints-modal" tabindex="-1" role="dialog" aria-labelledby="recipeints-modal-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="recipeints-modal-label">Recipients</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img class="loader" src="@Url.Content("//ssel-apps.eecs.umich.edu/static/images/ajax-loader.gif")" />
                <textarea class="form-control emails" spellcheck="false" style="height: 200px; display: none;"></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        setValues();

        function getSelectedValues() {
            var val = $(".selected-values").val();
            if (val)
                return JSON.parse(val);
            else
                return [];
        }

        function getSelectedTab() {
            return $("#tab1 .nav-link.active").data('name');
        }

        function setValues() {
            var values = getSelectedValues();

            if (values.length == 0)
                return;

            var tab = getSelectedTab();
            var val = 0;

            switch (tab) {
                case 'privilege':
                    $("#privilege .form-check-input").each(function () {
                        val = parseInt($(this).val());
                        if (values.indexOf(val) > -1)
                            $(this).prop("checked", true);
                    });
                    break;
                case 'community':
                    $("#community .form-check-input").each(function () {
                        val = parseInt($(this).val());
                        if (values.indexOf(val) > -1)
                            $(this).prop("checked", true);
                    });
                    break;
                case 'manager':
                    val = values[0];
                    $("#manager select option[value=" + val + "]").prop("selected", true);
                    break;
                case 'tools':
                    for (var i = 0; i < values.length; i++) {
                        val = values[i];
                        $("#tools select option[value=" + val + "]").prop("selected", true);
                    }
                    break;
                case 'inlab':
                    $("#inlab .form-check-input").each(function () {
                        val = parseInt($(this).val());
                        if (values.indexOf(val) > -1)
                            $(this).prop("checked", true);
                    });
                    break;
            }
        }

        function getValues(tab) {
            var values = [];
            var val = 0;

            switch (tab) {
                case 'privilege':
                    $("#privilege .form-check-input:checked").each(function () {
                        val = parseInt($(this).val());
                        values.push(val);
                    });
                    break;
                case 'community':
                    $("#community .form-check-input:checked").each(function () {
                        val = parseInt($(this).val());
                        values.push(val);
                    });
                    break;
                case 'manager':
                    val = parseInt($("#manager select").val());
                    values.push(val);
                    break;
                case 'tools':
                    values = $.map($("#tools select").val(), function (v) { return parseInt(v); });
                    break;
                case 'inlab':
                    $("#inlab .form-check-input:checked").each(function () {
                        val = parseInt($(this).val());
                        values.push(val);
                    });
                    break;
            }

            return values;
        }

        function combine(values) {
            return values.reduce(function (x, val) {
                return x | val;
            });
        }

        function getData() {
            var data = {
                "Privs": 0,
                "Communities": 0,
                "Manager": 0,
                "Tools": [],
                "InLab": []
            };

            var selectedTab = getSelectedTab();

            var values = getValues(selectedTab);

            switch (selectedTab) {
                case 'privilege':
                    data.Privs = combine(values);
                    break;
                case 'community':
                    data.Communities = combine(values);
                    break;
                case 'manager':
                    data.Manager = values[0];
                    break;
                case 'tools':
                    data.Tools = values;
                    break;
                case 'inlab':
                    data.InLab = values;
                    break;
            }

            return data;
        }

        $("#recipeints-modal").on("hidden.bs.modal", function (e) {
            var modal = $(this);
            $(".modal-body .loader", modal).show();
            $(".modal-body .emails", modal).val('').hide();
        }).on("shown.bs.modal", function (e) {
            var data = getData();

            var modal = $(this);

            $.ajax({
                "url": '@Url.Action("Recipients", "Ajax")',
                "method": "POST",
                "contentType": "application/json",
                "dataType": "json",
                "data": JSON.stringify(data)
            }).done(function (data) {
                var emails = $.map(data, function (x) { return x.Email });
                $(".modal-body .loader", modal).hide();
                $(".modal-body .emails", modal).val(emails.join('\n')).show();
            });
        });

        $('#tab1 a[data-toggle="tab"]').on("shown.bs.tab", function (e) {
            var selectedTab = $(e.target).data('name');
            $(".selected-tab").val(selectedTab);
        });

        $("#form1").on("submit", function (e) {
            var values = getValues(getSelectedTab());
            $(".selected-values").val(JSON.stringify(values));
        })
    </script>
}